- .gitignore
- package.json
- src/extension.ts
- test/execution/execution.test.ts
- test/gauge.test.ts
- registered new command `gauge.showReferences`.
- extension activates if manifest.json is found in workspace.
> Showing code references for steps in js files

- package.json
- src/commands.ts
- src/execution/gaugeExecution.ts
- src/execution/outputChannel.ts
- src/extension.ts
- test/execution/execution.test.ts
adds support for stopping execution, #56
> 56 stop execution

- src/execution/outputChannel.ts
- test/execution/outputChannel.test.ts
Error Path had two issues
1. Root Path was getting concatenated twice in some cases
2. Root Path was not getting concatenated in some cases
Fix has 2 components
1. Check if rootPath is already present in the filePath and if present don't add again
2. Regex was only modifying the first fine in a multi line stacktrace which is changed now
> Error Path will now have rootPath concatenated only once #79

- src/explorer/specExplorer.ts
* Vscode closes a file when it is deleted or moved hence file close event is captured and spec explorer refreshed
* When a new folder is added to the workspace spec explorer should reflect that
> Spec explorer to refresh on file move and deletion #111

- src/execution/debug.ts
- src/execution/gaugeExecution.ts
- src/extension.ts
* sleep added specifically for python since python debug server needs to be up before vscode tries to connect to it
* extracting language from manifest.json since the type field in debug configuration depends on the language
> Debugger for python added, getgauge/gauge-python#33

- src/constants.ts
- src/extension.ts
- src/terminal/terminal.ts
- src/ui/welcome/index.html
- src/welcome/welcome.ts
When gauge binaries are not found but gauge-vscode plugin is installed, welcome page shows a section where gauge install instructions are shown based on the OS.
> Showing gauge install instruction on welcome page when gauge is not installed

- package.json
- src/extension.ts
- src/ui/welcome/index.html
- src/welcome/welcome.ts
- src/welcome/welcomePageTokenReplace.ts
- test/welcome/welcomePageTokenReplace.test.ts
- Removed the `Toggle display of Welcome Page`
- Removed check box `Do not show this page until the next release`
- Adde a setting `gauge.welcome.showOn` with 3 values `newProjectLoad`,  `versionUpgrade` and  `never`
> Welcome page enhancements #166

- README.md
- package-lock.json
- package.json
- src/constants.ts
- src/file/specificationFileProvider.ts
- src/gaugeWorkspace.ts
- src/ui/welcome/index.html
- test/pages/welcome.test.ts
The specification can be created from the welcome page as well.
The help comments in the template can be turned off via config settings.
> Add command to create specification template. #162

- src/execution/gaugeExecutor.ts
- Fixed typo in Gauge-maven plugin args (changed DspecDirs to DspecsDir).
- Calculate specs dir path relative to the project root.
> Fix for, #319

- .travis.yml
- .vscode/launch.json
- package.json
- src/config/configProvider.ts
- test/index.ts
- test/runTest.ts
**Recommended settings**
```
{
"files.autoSave": "afterDelay",
"files.autoSaveDelay": 500
}
```
Until now Gauge VS Code used to set recommended settings for the user space.
Which made it harder for the user to work with other projects where they did not required the `autoSave` feature or needed different value for it than the `afterDelay`.
Now Gauge VS Code will set recommended settings only for the workspace instead of for the user.
> Fix for recommended settings for Gauge projects.

- README.md
- package.json
- src/constants.ts
- src/extension.ts
Fixes: #413 
The "Report issue" is not consistent as it
opens a browser. Plus it posts version info
with an opt in.
Remove this feature as it will be much easier
to report issues to the right repository
manually.
Also note. VS Code's "Report Issue" allows 
reporting issues with plugins.
> Remove report issue feature

- package-lock.json
- src/execution/gaugeExecutor.ts
- test/execution/execution.test.ts
I noticed that tests were failing as follows
```
1 failing
should reject execution when another is already in progress:
AssertionError [ERR_ASSERTION]: "Running the contributed command: 'gauge.execute' failed." == 'A Specification or Scenario is still running!'
+ expected - actual
-Running the contributed command: 'gauge.execute' failed.
+A Specification or Scenario is still running!
```
This seems to be happening because of https://github.com/getgauge/gauge-vscode/blob/59ee8cfe1fdd0428af6e4f8e95ff01802c4f4909/src/execution/gaugeExecutor.ts#L52-L54
This also does not display the custom error message for example the current version of the plugin shows
After this change
```
if (this.executing) {
window.showErrorMessage('A Specification or Scenario is still running!');
return …
```
> Return proper error messages on failure

- test/execution/execution.test.ts
Opening the folder in the test leads to exceeding the call stack size, as shown below.
As far as I can see, all the tests work fine without the line. Is there something I missed?
The line has been added in [this commit](https://github.com/getgauge/gauge-vscode/pull/540/commits/26dc9f68b3aee7f21b516eaf8becffcffe9e88dd#diff-b34366ebbae8aa3582f775836d5fa5b77be1a7a4d1c4655664f56b657284ab43R10).
- MacOS BigSur 11.5.2
- VSCode 1.59.0
- Node.js 16.6.1
```
[2021-08-14 01:03:03.289] [exthost] [error] RangeError: Maximum call stack size exceeded
at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:90:6651
at ReferenceProvider.dispose (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/exten …
```
> Execution test exceeds call stack size

- package.json
- src/constants.ts
- src/execution/debug.ts
- src/execution/lineProcessors.ts
- src/explorer/specExplorer.ts
Inline Run and Debug buttons in Spec Explorer to run/debug spec/scenario without opening files.
I could not add any tests for this because,
- Debug command tests could not wait for the debugger to detach.
- Scenario node tests will fail or work wrong after pack, because the `Scenario` class in the test code is not the same as the one in `extension.js`.
[Here's what I've done.](https://github.com/at6ue/gauge-vscode/blob/TEST_run-test-explorer-node/test/explorer/specExplorer.test.ts)
Using `false` on when clause might confuse the parser, but I used `false` to respect the existing implementations.
https://github.com/microsoft/vscode/issues/45119
I modified `lineProcessor.ts` because I noticed VSCode show nothing there: `window.showErrorMessage` cannot handle `Error` object.
I was confused …
> Add Run and Debug buttons to Spec Explorer

- package.json
- src/execution/debug.ts
Fix issue #726. `Uri.parse` added in #700 should not be used for file paths.
Since the bug affects ALL Windows users, please consider releasing this as soon as possible.
> Fix file path handling when starting the debugger on Windows file system

- package.json
- src/execution/gaugeExecutor.ts
The file path of the report was handled wrongly as in #737.
Nothing has happened when Windows users execute "Show Last Run Report" command or click on the status bar.
`getReportPath` is expected to return only a file path generated by [html-report plugin](https://github.com/getgauge/html-report/blob/baa4f41d192296241ef14b0a1364cb1db80a8d5b/htmlReport.go#L73), as far as I have found.
Only tested manually on Mac OS X and Windows 10.
> Fix file path handling for reports on Windows

- package-lock.json
- package.json
- test/runTest.ts
I found that the path to the test workspace was wrong while digging into the cause of test failure in #736.
The failure log was
```
1) Gauge Execution Tests
should execute given specification:
Error: command 'gauge.execute' not found
...
```
This is probably due to the extension not being activated at that time.
`testWorkspace` should be assigned `test/testdata/sampleProject` in order to activate the extension as soon as `manifest.json` is found in the workspace **root**.
I am not sure if this is perfect, but it should improve the test stability.
I also found that `vscode-test` was renamed to `@vscode/test-electron` [from 1.6.2](https://github.com/microsoft/vscode-test/commit/614274c58f9300756209e468fcde566fb452518e#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R2). …
> Fix workspace path for testing

- .vscode/settings.json
- package-lock.json
- package.json
- src/annotator/generateStub.ts
- src/execution/gaugeExecutor.ts
- src/explorer/specExplorer.ts
- src/file/specificationFileProvider.ts
- src/gaugeWorkspace.proposed.ts
- src/gaugeWorkspace.ts
- tslint.json
Upgrades all dependencies to the newest state that doesn't require large changes.
The largest change is the removal of `await client.onReady();` caused by  https://github.com/microsoft/vscode-languageserver-node/blob/main/README.md#3170-protocol-800-json-rpc-800-client-and-800-server
After this PR, we could move to eslint (and prettier?) as tslint is deprecated.
> upgrades dependencies

- package.json
- src/extension.ts
- src/gaugeWorkspace.ts
Currently, LSP clients are disposed of within `gaugeWorkspace.ts` upon extension disposal.
This doesn't cover all cases and can leave the clients and server running.
I can observe this in our environment where `gauge-vscode` is deployed in a remote development setup. A window reload will dispose of all UI extensions but won't dispose of extensions running in the remote extension host mechanism, these are deactivated. 
The official [multi server LSP example](https://github.com/microsoft/vscode-extension-samples/blob/4721ef0c450f36b5bce2ecd5be4f0352ed9e28ab/lsp-multi-server-sample/client/src/extension.ts#L120) hoists the client map into `extension.ts` and explicitly disposes all resources on deactivation. 
This PR moves to this explicit deactivation strategy.
> moves client disposal into deactivate method

- package-lock.json
- package.json
the automatic upgrade bumped the `@types/vscode` and `"engines": {"vscode": "^1.63.1"}` which removed all backwards compatibility
this change can be savely reverted as this extension doesn't use any newly introduced vscode interfaces
> reverts vscode type upgrade to restore version compatibility

- .github/dependabot.yml
- .github/workflows/vscode.yml
- README.md
- package-lock.json
- package.json
- src/gaugeWorkspace.proposed.ts
- src/protocol/gauge.proposed.ts
- test/execution/execution.test.ts
- test/runTest.ts
- tsconfig.json
As mentioned by @chadlwilson, vscode and the associated LSP projects aren't adhering to semver.
Mismatching `@types/vscode` and `engines['vscode']` versions are caught by the build process.
This isn't the case for a `engines['vscode']` value that is lower than the `@types/vscode` version required by `vscode-jsonrpc`, `vscode-languageclient`, and `vscode-languageclient-protocol`.
Starting the plugin with a "compatible" vscode version (according to `engines['vscode']`) will fail during runtime with the following error 
`Error: The language client requires VS Code version ^1.82.0 but received version 1.63.1.`
This PR adds:
1. A new npm script, `npm run compatibilityTest`, which executes the test suite using the minimum vscode version specified in package.json. This is kept separate in order …
> Pin and test all vscode packages

- package-lock.json
- package.json
- src/annotator/generateStub.ts
Hopefully fixes #900
Clipboardy 4 seems to involve use of `import.meta.url` which our webpack configuration does not current handle elegantly, and seems to cause the extension to fail to load on Windows due to use of pre-compiled POSIX paths rather than something dynamic. Downgrading for now rather than working around, although possibly a more direct import of just
https://github.com/getgauge/gauge-vscode/issues/900#issuecomment-1814159373
I'm not even sure if the clipboard stuff works, as the platform specific native binaries don't appear to be bundled with the extension, so it's a bit beyond me as to how it could work?
> Fix extension loading on Windows

- package-lock.json
- package.json
- src/annotator/generateStub.ts
- test/references.test.ts
Follow-up to #901 replacing the non-functional use of Clipboardy with VSCode's own API for basic clipboard interaction introduced as experimental in ~Oct 2018 via https://github.com/microsoft/vscode/issues/217. See https://code.visualstudio.com/api/references/vscode-api#Clipboard
> Replace clipboardy with use of native vscode API

- .vscodeignore
- package-lock.json
- package.json
See https://www.npmjs.com/package/vsce
Seems no major changes. Only dev tooling so probably not necessary to release at this stage, although likely changes the built VSIX package and the publishing slightly.
> Bump vsce from 2.15 to 2.22

- language-configuration.json
- package.json
- src/extension.ts
- src/semanticTokensProvider.ts
Hi!
@sriv @zabil 
Addressing this issue:
https://github.com/getgauge/gauge-vscode/issues/884
Implemented syntax highlighting. All token-matching is done on extensions side. Extension provides default colors that works fine with VSC default (dark) theme, but can be overridden in settings.json.
Also, during test development I often want to temporarily disable one or multiple steps in a scenario. Although it's not technically markdown I simply put the common "//" in front of the step (and any table) and then the runner ignores it. I've added a binding to VSC short-cut for comment/un-comment that adds "//" at the beginning of the line (which makes it possible to disable many steps quickly my selecting multiple lines). I find it very convenient and I don't see that it does any harm. 
Default …
> Adding syntax highlighting

- language-configuration.json
- package-lock.json
- package.json
- src/extension.ts
- src/gaugeWorkspace.ts
- src/semanticTokensProvider.ts
@sriv 
1. Added a setting to the Extension called "gauge.formatting.skipEmptyLineInsertions".
2. Added code for sending any "gauge" settings in settings.json to the Gauge server.
For further details:
Issue: https://github.com/getgauge/gauge/issues/2693
Merged PR in Gauge: https://github.com/getgauge/gauge/pull/2692
With the addition one can now control if the formatting of spec-files should add empty lines around "tags" and before "table" entities, (as before) or if you want to disable this when formatting.
> Added setting for config Gauge formatter and send the settings to Gauge server.

- package-lock.json
- package.json
- src/extension.ts
- src/semanticTokensProvider.ts
Fix for: https://github.com/getgauge/gauge-vscode/issues/1042
@sriv Please merge when you have time. Sorry for the mistake & inconvenience...
> Bug fix for issue 1042 - Gauge comment syntax highlighter conflicted with default comment highlighter for other langauges.

- package-lock.json
- package.json
It's been 18 months now since 1.82.0. The next version minimum is `1.82.x` for compatibility with language client v9. https://code.visualstudio.com/updates/v1_82
https://github.com/microsoft/vscode-languageserver-node?tab=readme-ov-file#3174-protocol-820-json-rpc-900-client-and-900-server
Includes these fixes: https://github.com/microsoft/vscode-languageserver-node/milestone/46?closed=1
> Bump VSCode requirement to 1.82.0+ (August 2023)

- package-lock.json
- package.json
- src/cli.ts
Didn't pay enough attention to the fact that this is eagerly invoked every time even for maven which many users will neither have nor need; so probably not worth including.
Fixes #1054, partially reverts #1052
> fix: Revert addition of visual error when commands cannot be found

- package-lock.json
- package.json
- src/project/gradleProject.ts
- src/project/mavenProject.ts
Fixes #1064
Apparently this similar approach via `execSync` without special options worked earlier, as apparently in NodeJS `exec` seems to always run with a shell even though `spawn` (used to locate the commands) does not.
> fix: Correct execing of Maven/Gradle
