- src/execution/outputChannel.ts
- test/execution/outputChannel.test.ts
Fixes #23 by converting relative paths to absolute.
> resolve relative to abs path in error stacktrace

- README.md
- package.json
- src/execution/gaugeExecution.ts
- src/extension.ts
- test/execution/execution.test.ts
fix for following issues :
#24
#34
#37
> Execution commands to run scenario, specification and report issue 

- appveyor.yml
- package.json
- src/commands.ts
- src/execution/outputChannel.ts
- src/explorer/specExplorer.ts
- src/extension.ts
- test/execution/outputChannel.test.ts
* Run Scenarios changed to singular
* Spec Explorer refreshed on File Save
* External library paths not appended with project root path
* When quick pick is closed with esc no error is shown
* Run from spec explorer does not show project list
* Navigation to spec from explorer fixed
> Run scenario and refresh spec explorer on file save

- .gitignore
- package.json
- src/commands.ts
- src/constants.ts
- src/execution/gaugeExecution.ts
- src/explorer/specExplorer.ts
- src/extension.ts
- src/gaugeVersion.ts
- src/refactor/extractConcept.ts
- src/refactor/workspaceEditor.ts
- src/stubImplementation.ts
- src/types/fileListItem.ts
- src/welcome/welcome.ts
- webpack.config.js
Shows CodeAction on selection.
Shows input box to add concept name.
Shows quick pick to concept file (existing or new).
Make an extractConcpet request and apply workspace changes.
Shows error if the selection is not valid for extraction.
> Extract concept

- .travis.yml
- appveyor.yml
- package.json
- src/extension.ts
- src/pages/page.ts
- src/pages/provider.ts
- src/pages/report.ts
- src/pages/welcome.ts
- src/pages/welcomePageTokenReplace.ts
- src/ui/welcome/index.html
- test/pages/welcomePageTokenReplace.test.ts
- hides some commands when gauge is not activated yet. TODO - these commands should be made more context specific.
- welcome page disables "Run all Specification" when a gauge project is not opened.
> 247 welcome page command

- appveyor.yml
- package-lock.json
- package.json
- src/constants.ts
- src/extension.ts
- src/gaugeVersion.ts
- src/gaugeWorkspace.ts
- src/util.ts
- tries to execute `gauge` to find the correct gauge command.
> fixing issue with gauge installed via node, #290

- appveyor.yml
- package-lock.json
- package.json
- src/annotator/generateStub.ts
- src/config/configProvider.ts
- src/explorer/specExplorer.ts
- src/extension.ts
- src/file/specificationFileProvider.ts
- src/gaugeReference.ts
- src/gaugeState.ts
- src/gaugeVersion.ts
- src/gaugeWorkspace.proposed.ts
- src/init/projectInit.ts
- src/pages/page.ts
- src/pages/provider.ts
- src/pages/report.ts
- src/pages/welcome.ts
- src/pages/welcomePageTokenReplace.ts
- src/refactor/workspaceEditor.ts
- src/terminal/terminal.ts
- src/types/fileListItem.ts
- test/execution/execution.test.ts
- test/gauge.test.ts
- test/pages/welcome.test.ts
- test/pages/welcomePageTokenReplace.test.ts
- test/references.test.ts
- webpack.config.js
- update vscode engine to latest
- cleanup code and change uglify webpack plugin
- fixes security warning
> Dependency update

- package-lock.json
- package.json
- src/annotator/generateStub.ts
- src/execution/gaugeExecutor.ts
- src/explorer/specExplorer.ts
- src/extension.ts
- src/gaugeReference.ts
- src/gaugeWorkspace.ts
- src/util.ts
- test/references.test.ts
- A user opens any Gauge document.
- Determine the Gauge project root from the document path.
- Start an LSP server for the Gauge project.
> Support nested Gauge projects within a Workspace Folder.

- package.json
- src/execution/debug.ts
- src/execution/gaugeExecutor.ts
- src/init/projectInit.ts
> Stopping the current execution.

- package-lock.json
- src/config/gaugeProjectConfig.ts
- src/gaugeWorkspace.ts
getting correct java version. 
JavaConfig files added only if it not a… maven project, getgauge/gauge-java#257
> Fix issues with Java 12 in VSCode.

- src/execution/debug.ts
- src/init/projectInit.ts
This add typescript support. For more info about the typescript runner refer https://bugdiver.github.io/gauge-ts
> Added typescript support.

- src/welcomeNotifications.ts
Fix the installation instructions for #352
> #352 Fix URL to point to the right URL

- package.json
fix for #426 is pushed to master, this PR is to make a release﻿
> release 0.0.13

- src/cli.ts
- src/constants.ts
Signed-off-by: NivedhaSenthil <nivedhasenthil@gmail.com>
> #428 fix command used on windows

- package-lock.json
- package.json
- src/constants.ts
- src/gaugeWorkspace.ts
- src/project/gaugeProject.ts
- src/project/gradleProject.ts
- src/project/mavenProject.ts
- test/project.test.ts
Signed-off-by: Dharmendra Singh <dharmenn@thoughtworks.com>
> Set gauge_custom_classpath env for maven and gradle project.

- src/execution/debug.ts
Added capability to specify source file map in launch.json for a csharp project for debugging capability.
> #436:  Added capability to add source file map for csharp in launch.json

- package-lock.json
- package.json
- src/cli.ts
- src/constants.ts
- src/init/projectInit.ts
- src/welcomeNotifications.ts
Needs getgauge/gauge#1640 to be merged
> Update project initialisation.

- src/gaugeWorkspace.ts
> Add env to continue runner on build failures.

- src/file/specificationFileProvider.ts
Fixes: #466
Signed-off-by: Zabil Cheriya Maliackal <zabilcm@gmail.com>
> Fix typo for specification template file

- package-lock.json
- package.json
- src/execution/gaugeExecutor.ts
- test/execution/execution.test.ts
- increase timeout for execution tests
- bump version for a release
> Clean up execution processes properly 

- package-lock.json
- package.json
- src/execution/gaugeExecutor.ts
- test/execution/execution.test.ts
- revert changes that made execution happen in separate process group
> Fix child process

- src/execution/gaugeExecutor.ts
Signed-off-by: NivedhaSenthil <nivedhasenthil@gmail.com>
> Kill process group for non windows platform

- package-lock.json
- package.json
- src/config/gaugeProjectConfig.ts
> Avoid classpath file restoring if exists

- .github/workflows/vscode.yml
Signed-off-by: Zabil Cheriya Maliackal <zabilcm@gmail.com>
> Use Gauge setup action

- .github/workflows/githubRelease.yml
Signed-off-by: NivedhaSenthil <nivedhasenthil@gmail.com>
> update node version for release

- package-lock.json
- package.json
- src/refactor/workspaceEditor.ts
Signed-off-by: sriv <srikanth.ddit@gmail.com>
> dependencies updated

- .github/dependabot.yml
- .github/workflows/githubRelease.yml
- .github/workflows/vscode.yml
- package-lock.json
- package.json
- src/file/specificationFileProvider.ts
- test/index.ts
Close to the bare minimum changes to
- resolve npm audit vulnerability noise
- get the GH actions build going
- update a few low hanging fruit easy dependencies
> Build with Node 20 and Go 1.21

- package.json
see https://github.com/getgauge/gauge-vscode/pull/891#issuecomment-1795557383
> bump version for rerelease to reset vscode engine version

- package.json
> Bump version to trigger a release

- src/cli.ts
- Minor style/brevity/typo tweaks
- Adds a visual cue if gauge/mvn cannot be found per #1049
> Make some minor style/readability tidies to command spawning code

- package-lock.json
- package.json
- src/cli.ts
- src/execution/gaugeExecutor.ts
- src/gaugeWorkspace.ts
- src/init/projectInit.ts
- src/project/gaugeProject.ts
- test/cli.test.ts
- test/commands/test_command
- test/commands/test_command.bat
- test/commands/test_command.cmd
> fix: Correct spawning of Windows binaries by batch/cmd with spaces
